### ISSUE TITLE
Add license to repo

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog-ui#25]

**Comment by robertgv** [comment]
@MrPowers Should be "Apache License 2.0"?

Can I start with this one? 😄

**Comment by yc-shawn** [comment]
@robertgv this should be good: https://github.com/unitycatalog/unitycatalog/blob/main/LICENSE

**Comment by MrPowers** [comment]
@robertgv - yea, assigned this one to you!

**Comment by robertgv** [comment]
@yc-shawn @MrPowers Can I contribute directly or do I need to fork?

**Comment by yc-shawn** [comment]
@robertgv just create a PR against main branch

**Comment by MrPowers** [comment]
@robertgv - you can just use a fork if you don't have write access to the repo.

**Comment by robertgv** [comment]
@yc-shawn Had to do via a fork because of permissions.
