### ISSUE TITLE
Delete Volume

### ISSUE THREAD

**Issue by jamieknight-db** [unitycatalog/unitycatalog-ui#33]

**Comment by xx-tabular** [comment]
I can take this one

**Comment by xx-db** [comment]
I can take this one

**Comment by JuanPabloDiaz** [comment]
Is it okey if I work on this one?
Looking for a **first issue** to start

**Comment by jamieknight-db** [comment]
@JuanPabloDiaz I believe @xx-db is already working on this issue. I will get some designs for the update description tickets and those would be great first issues.
