### ISSUE TITLE
Update catalog description

### ISSUE THREAD

**Issue by jamieknight-db** [unitycatalog/unitycatalog-ui#38]
<img width="594" alt="Screenshot 2024-07-29 at 11 53 39 AM" src="https://github.com/user-attachments/assets/1fcdf90d-81c0-4d2c-aa6a-503fe3fed5a3">
<img width="454" alt="Screenshot 2024-07-29 at 11 53 11 AM" src="https://github.com/user-attachments/assets/cda05466-c389-4295-ac93-fae294cf7671">
<img width="1082" alt="Screenshot 2024-07-29 at 11 53 03 AM" src="https://github.com/user-attachments/assets/50ff4ae3-0795-4d33-903d-31b91fd2fd2e">

**Comment by jamieknight-db** [comment]
@JuanPabloDiaz I uploaded design screenshots. Would you like to take this one?

**Comment by JuanPabloDiaz** [comment]
sure

**Comment by jamieknight-db** [comment]
@xx-db can you take this first update description issue so others have code to reference for other assets?

**Comment by xx-db** [comment]
yes, I can take this one
