### ISSUE TITLE
Update schema description

### ISSUE THREAD

**Issue by jamieknight-db** [unitycatalog/unitycatalog-ui#39]
<img width="594" alt="Screenshot 2024-07-29 at 11 53 39 AM" src="https://github.com/user-attachments/assets/75f03855-f780-4356-9c36-aec0f221a1f1">
<img width="454" alt="Screenshot 2024-07-29 at 11 53 11 AM" src="https://github.com/user-attachments/assets/6bf53cec-eb1b-4256-ba4e-d255475d9c63">
<img width="1082" alt="Screenshot 2024-07-29 at 11 53 03 AM" src="https://github.com/user-attachments/assets/580cbe9c-ba70-4b74-83fa-53cdfeaf8022">

Design is for catalog, but is the same for schema.

**Comment by JuanPabloDiaz** [comment]
may I work on this please?

**Comment by jamieknight-db** [comment]
@JuanPabloDiaz it's all yours!

**Comment by jamieknight-db** [comment]
@JuanPabloDiaz are you still planning to work on this? Did you see the catalog description PR that was merged? You can use that as a guide for schema description.

**Comment by JuanPabloDiaz** [comment]
yes @jamieknight-db. I will work on it. Thank you
