### ISSUE TITLE
Update volume description

### ISSUE THREAD

**Issue by jamieknight-db** [unitycatalog/unitycatalog-ui#41]
<img width="594" alt="Screenshot 2024-07-29 at 11 53 39 AM" src="https://github.com/user-attachments/assets/3480cd68-4fe2-43d2-a188-3b5fd64c190e">
<img width="454" alt="Screenshot 2024-07-29 at 11 53 11 AM" src="https://github.com/user-attachments/assets/554812c5-a118-4d8b-bdb0-288de8d1dcb7">
<img width="1082" alt="Screenshot 2024-07-29 at 11 53 03 AM" src="https://github.com/user-attachments/assets/52a1048c-3172-4573-bbfb-5e6307d80257">

Design is for catalog but will be the same for volume

**Comment by vksx** [comment]
I can take this one.
